"""
ONE-TIME setup script: pre-synthesizes a small set of short Hindi filler
acknowledgments ("haan ji,", "hmm,", "theek hai,", ...) through the SAME
Svara TTS backend agent_api.py already uses, and bakes the resulting audio
into filler_audio.py as ready-to-play base64 clips.

Why pre-synthesize instead of generating a filler on the fly each turn:
Svara itself takes ~1.6-5s to synthesize even a short sentence (see
TTS_FIRST_CHUNK in call logs), so synthesizing a filler live would just
replace one wait with another. Baking it in ahead of time means playing it
costs ~0ms at request time -- pure cache lookup, no synthesis.

Run this ONCE on the DGX, in any env with `requests` and network access to
the Svara TTS adapter (port 8003, must already be running):

    python generate_fillers.py

It writes filler_audio.py in the same directory. Re-run any time you want
to change the phrasing or pick up a different voice.
"""
import base64
import json

import requests

TTS_URL = "http://127.0.0.1:8003/synthesize"

# Short, natural Hindi conversational acknowledgments -- the kind a real
# phone agent says while starting to think, not full sentences. Kept under
# ~1s of audio each so they mask latency without adding noticeable delay
# themselves, even on turns where the real reply would have been fast.
FILLER_PHRASES = [
    "जी हाँ,",
    "हम्म्म,",
    "ठीक है,",
    "जी बिलकुल,",
]

OUTPUT_FILE = "filler_audio.py"


def synthesize(text: str) -> dict:
    resp = requests.post(TTS_URL, json={"text": text}, timeout=120)
    resp.raise_for_status()
    result = resp.json()
    if result.get("status") != "success" or not result.get("audio_b64"):
        raise RuntimeError(f"TTS failed for '{text}': {result}")
    return {
        "text": text,
        "audio_b64": result["audio_b64"],
        "sample_rate": result.get("sample_rate", 22050),
    }


def main():
    print(f"Synthesizing {len(FILLER_PHRASES)} filler phrase(s) via {TTS_URL} ...")
    fillers = []
    for phrase in FILLER_PHRASES:
        print(f"  - '{phrase}'")
        fillers.append(synthesize(phrase))

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(
            '"""\n'
            "Pre-synthesized filler audio clips (generated by generate_fillers.py).\n"
            "Do not edit by hand; re-run generate_fillers.py to regenerate.\n"
            '"""\n\n'
        )
        f.write(f"FILLERS = {json.dumps(fillers, ensure_ascii=False, indent=4)}\n")

    total_bytes = sum(len(base64.b64decode(fl["audio_b64"])) for fl in fillers)
    print(f"\nWrote {OUTPUT_FILE} ({len(fillers)} clip(s), {total_bytes/1024:.1f} KB decoded audio).")
    print("Restart agent_api.py to pick it up.")


if __name__ == "__main__":
    main()
